static const char *
getRuntimeApiKindString(CUpti_CallbackId kind)
{
  switch (kind) 
  {
    case CUPTI_RUNTIME_TRACE_CBID_INVALID:
      return "INVALID";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDriverGetVersion_v3020:
      return "cudaDriverGetVersion_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaRuntimeGetVersion_v3020:
      return "cudaRuntimeGetVersion_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceCount_v3020:
      return "cudaGetDeviceCount_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceProperties_v3020:
      return "cudaGetDeviceProperties_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaChooseDevice_v3020:
      return "cudaChooseDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetChannelDesc_v3020:
      return "cudaGetChannelDesc_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaCreateChannelDesc_v3020:
      return "cudaCreateChannelDesc_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaConfigureCall_v3020:
      return "cudaConfigureCall_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetupArgument_v3020:
      return "cudaSetupArgument_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetLastError_v3020:
      return "cudaGetLastError_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaPeekAtLastError_v3020:
      return "cudaPeekAtLastError_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetErrorString_v3020:
      return "cudaGetErrorString_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunch_v3020:
      return "cudaLaunch_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetCacheConfig_v3020:
      return "cudaFuncSetCacheConfig_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFuncGetAttributes_v3020:
      return "cudaFuncGetAttributes_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetDevice_v3020:
      return "cudaSetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetDevice_v3020:
      return "cudaGetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetValidDevices_v3020:
      return "cudaSetValidDevices_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetDeviceFlags_v3020:
      return "cudaSetDeviceFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMalloc_v3020:
      return "cudaMalloc_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMallocPitch_v3020:
      return "cudaMallocPitch_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFree_v3020:
      return "cudaFree_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMallocArray_v3020:
      return "cudaMallocArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFreeArray_v3020:
      return "cudaFreeArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMallocHost_v3020:
      return "cudaMallocHost_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFreeHost_v3020:
      return "cudaFreeHost_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaHostAlloc_v3020:
      return "cudaHostAlloc_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaHostGetDevicePointer_v3020:
      return "cudaHostGetDevicePointer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaHostGetFlags_v3020:
      return "cudaHostGetFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemGetInfo_v3020:
      return "cudaMemGetInfo_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy_v3020:
      return "cudaMemcpy_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2D_v3020:
      return "cudaMemcpy2D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArray_v3020:
      return "cudaMemcpyToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArray_v3020:
      return "cudaMemcpy2DToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArray_v3020:
      return "cudaMemcpyFromArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArray_v3020:
      return "cudaMemcpy2DFromArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyArrayToArray_v3020:
      return "cudaMemcpyArrayToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DArrayToArray_v3020:
      return "cudaMemcpy2DArrayToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbol_v3020:
      return "cudaMemcpyToSymbol_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbol_v3020:
      return "cudaMemcpyFromSymbol_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyAsync_v3020:
      return "cudaMemcpyAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArrayAsync_v3020:
      return "cudaMemcpyToArrayAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArrayAsync_v3020:
      return "cudaMemcpyFromArrayAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DAsync_v3020:
      return "cudaMemcpy2DAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArrayAsync_v3020:
      return "cudaMemcpy2DToArrayAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArrayAsync_v3020:
      return "cudaMemcpy2DFromArrayAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbolAsync_v3020:
      return "cudaMemcpyToSymbolAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbolAsync_v3020:
      return "cudaMemcpyFromSymbolAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset_v3020:
      return "cudaMemset_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset2D_v3020:
      return "cudaMemset2D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemsetAsync_v3020:
      return "cudaMemsetAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset2DAsync_v3020:
      return "cudaMemset2DAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetSymbolAddress_v3020:
      return "cudaGetSymbolAddress_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetSymbolSize_v3020:
      return "cudaGetSymbolSize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaBindTexture_v3020:
      return "cudaBindTexture_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaBindTexture2D_v3020:
      return "cudaBindTexture2D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaBindTextureToArray_v3020:
      return "cudaBindTextureToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaUnbindTexture_v3020:
      return "cudaUnbindTexture_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureAlignmentOffset_v3020:
      return "cudaGetTextureAlignmentOffset_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureReference_v3020:
      return "cudaGetTextureReference_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaBindSurfaceToArray_v3020:
      return "cudaBindSurfaceToArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetSurfaceReference_v3020:
      return "cudaGetSurfaceReference_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLSetGLDevice_v3020:
      return "cudaGLSetGLDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLRegisterBufferObject_v3020:
      return "cudaGLRegisterBufferObject_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLMapBufferObject_v3020:
      return "cudaGLMapBufferObject_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLUnmapBufferObject_v3020:
      return "cudaGLUnmapBufferObject_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLUnregisterBufferObject_v3020:
      return "cudaGLUnregisterBufferObject_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLSetBufferObjectMapFlags_v3020:
      return "cudaGLSetBufferObjectMapFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLMapBufferObjectAsync_v3020:
      return "cudaGLMapBufferObjectAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLUnmapBufferObjectAsync_v3020:
      return "cudaGLUnmapBufferObjectAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaWGLGetDevice_v3020:
      return "cudaWGLGetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsGLRegisterImage_v3020:
      return "cudaGraphicsGLRegisterImage_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsGLRegisterBuffer_v3020:
      return "cudaGraphicsGLRegisterBuffer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsUnregisterResource_v3020:
      return "cudaGraphicsUnregisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceSetMapFlags_v3020:
      return "cudaGraphicsResourceSetMapFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsMapResources_v3020:
      return "cudaGraphicsMapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsUnmapResources_v3020:
      return "cudaGraphicsUnmapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedPointer_v3020:
      return "cudaGraphicsResourceGetMappedPointer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsSubResourceGetMappedArray_v3020:
      return "cudaGraphicsSubResourceGetMappedArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaVDPAUGetDevice_v3020:
      return "cudaVDPAUGetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaVDPAUSetVDPAUDevice_v3020:
      return "cudaVDPAUSetVDPAUDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsVDPAURegisterVideoSurface_v3020:
      return "cudaGraphicsVDPAURegisterVideoSurface_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsVDPAURegisterOutputSurface_v3020:
      return "cudaGraphicsVDPAURegisterOutputSurface_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDevice_v3020:
      return "cudaD3D11GetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDevices_v3020:
      return "cudaD3D11GetDevices_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D11SetDirect3DDevice_v3020:
      return "cudaD3D11SetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D11RegisterResource_v3020:
      return "cudaGraphicsD3D11RegisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDevice_v3020:
      return "cudaD3D10GetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDevices_v3020:
      return "cudaD3D10GetDevices_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10SetDirect3DDevice_v3020:
      return "cudaD3D10SetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D10RegisterResource_v3020:
      return "cudaGraphicsD3D10RegisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10RegisterResource_v3020:
      return "cudaD3D10RegisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10UnregisterResource_v3020:
      return "cudaD3D10UnregisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10MapResources_v3020:
      return "cudaD3D10MapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10UnmapResources_v3020:
      return "cudaD3D10UnmapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceSetMapFlags_v3020:
      return "cudaD3D10ResourceSetMapFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetSurfaceDimensions_v3020:
      return "cudaD3D10ResourceGetSurfaceDimensions_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedArray_v3020:
      return "cudaD3D10ResourceGetMappedArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedPointer_v3020:
      return "cudaD3D10ResourceGetMappedPointer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedSize_v3020:
      return "cudaD3D10ResourceGetMappedSize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedPitch_v3020:
      return "cudaD3D10ResourceGetMappedPitch_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDevice_v3020:
      return "cudaD3D9GetDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDevices_v3020:
      return "cudaD3D9GetDevices_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9SetDirect3DDevice_v3020:
      return "cudaD3D9SetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDirect3DDevice_v3020:
      return "cudaD3D9GetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D9RegisterResource_v3020:
      return "cudaGraphicsD3D9RegisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9RegisterResource_v3020:
      return "cudaD3D9RegisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnregisterResource_v3020:
      return "cudaD3D9UnregisterResource_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9MapResources_v3020:
      return "cudaD3D9MapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnmapResources_v3020:
      return "cudaD3D9UnmapResources_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceSetMapFlags_v3020:
      return "cudaD3D9ResourceSetMapFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetSurfaceDimensions_v3020:
      return "cudaD3D9ResourceGetSurfaceDimensions_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedArray_v3020:
      return "cudaD3D9ResourceGetMappedArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedPointer_v3020:
      return "cudaD3D9ResourceGetMappedPointer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedSize_v3020:
      return "cudaD3D9ResourceGetMappedSize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedPitch_v3020:
      return "cudaD3D9ResourceGetMappedPitch_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9Begin_v3020:
      return "cudaD3D9Begin_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9End_v3020:
      return "cudaD3D9End_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9RegisterVertexBuffer_v3020:
      return "cudaD3D9RegisterVertexBuffer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnregisterVertexBuffer_v3020:
      return "cudaD3D9UnregisterVertexBuffer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9MapVertexBuffer_v3020:
      return "cudaD3D9MapVertexBuffer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnmapVertexBuffer_v3020:
      return "cudaD3D9UnmapVertexBuffer_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadExit_v3020:
      return "cudaThreadExit_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetDoubleForDevice_v3020:
      return "cudaSetDoubleForDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaSetDoubleForHost_v3020:
      return "cudaSetDoubleForHost_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadSynchronize_v3020:
      return "cudaThreadSynchronize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadGetLimit_v3020:
      return "cudaThreadGetLimit_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadSetLimit_v3020:
      return "cudaThreadSetLimit_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreate_v3020:
      return "cudaStreamCreate_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamDestroy_v3020:
      return "cudaStreamDestroy_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamSynchronize_v3020:
      return "cudaStreamSynchronize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamQuery_v3020:
      return "cudaStreamQuery_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventCreate_v3020:
      return "cudaEventCreate_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventCreateWithFlags_v3020:
      return "cudaEventCreateWithFlags_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventRecord_v3020:
      return "cudaEventRecord_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventDestroy_v3020:
      return "cudaEventDestroy_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventSynchronize_v3020:
      return "cudaEventSynchronize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventQuery_v3020:
      return "cudaEventQuery_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventElapsedTime_v3020:
      return "cudaEventElapsedTime_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMalloc3D_v3020:
      return "cudaMalloc3D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMalloc3DArray_v3020:
      return "cudaMalloc3DArray_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset3D_v3020:
      return "cudaMemset3D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset3DAsync_v3020:
      return "cudaMemset3DAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3D_v3020:
      return "cudaMemcpy3D_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DAsync_v3020:
      return "cudaMemcpy3DAsync_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadSetCacheConfig_v3020:
      return "cudaThreadSetCacheConfig_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamWaitEvent_v3020:
      return "cudaStreamWaitEvent_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDirect3DDevice_v3020:
      return "cudaD3D11GetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDirect3DDevice_v3020:
      return "cudaD3D10GetDirect3DDevice_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaThreadGetCacheConfig_v3020:
      return "cudaThreadGetCacheConfig_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaPointerGetAttributes_v4000:
      return "cudaPointerGetAttributes_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaHostRegister_v4000:
      return "cudaHostRegister_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaHostUnregister_v4000:
      return "cudaHostUnregister_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceCanAccessPeer_v4000:
      return "cudaDeviceCanAccessPeer_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceEnablePeerAccess_v4000:
      return "cudaDeviceEnablePeerAccess_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceDisablePeerAccess_v4000:
      return "cudaDeviceDisablePeerAccess_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaPeerRegister_v4000:
      return "cudaPeerRegister_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaPeerUnregister_v4000:
      return "cudaPeerUnregister_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaPeerGetDevicePointer_v4000:
      return "cudaPeerGetDevicePointer_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyPeer_v4000:
      return "cudaMemcpyPeer_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyPeerAsync_v4000:
      return "cudaMemcpyPeerAsync_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeer_v4000:
      return "cudaMemcpy3DPeer_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeerAsync_v4000:
      return "cudaMemcpy3DPeerAsync_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceReset_v3020:
      return "cudaDeviceReset_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSynchronize_v3020:
      return "cudaDeviceSynchronize_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetLimit_v3020:
      return "cudaDeviceGetLimit_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetLimit_v3020:
      return "cudaDeviceSetLimit_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetCacheConfig_v3020:
      return "cudaDeviceGetCacheConfig_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetCacheConfig_v3020:
      return "cudaDeviceSetCacheConfig_v3020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaProfilerInitialize_v4000:
      return "cudaProfilerInitialize_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaProfilerStart_v4000:
      return "cudaProfilerStart_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaProfilerStop_v4000:
      return "cudaProfilerStop_v4000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetByPCIBusId_v4010:
      return "cudaDeviceGetByPCIBusId_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetPCIBusId_v4010:
      return "cudaDeviceGetPCIBusId_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGLGetDevices_v4010:
      return "cudaGLGetDevices_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaIpcGetEventHandle_v4010:
      return "cudaIpcGetEventHandle_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaIpcOpenEventHandle_v4010:
      return "cudaIpcOpenEventHandle_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaIpcGetMemHandle_v4010:
      return "cudaIpcGetMemHandle_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaIpcOpenMemHandle_v4010:
      return "cudaIpcOpenMemHandle_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaIpcCloseMemHandle_v4010:
      return "cudaIpcCloseMemHandle_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaArrayGetInfo_v4010:
      return "cudaArrayGetInfo_v4010";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetSharedMemConfig_v4020:
      return "cudaFuncSetSharedMemConfig_v4020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetSharedMemConfig_v4020:
      return "cudaDeviceGetSharedMemConfig_v4020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetSharedMemConfig_v4020:
      return "cudaDeviceSetSharedMemConfig_v4020";
    case CUPTI_RUNTIME_TRACE_CBID_cudaCreateTextureObject_v5000:
      return "cudaCreateTextureObject_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDestroyTextureObject_v5000:
      return "cudaDestroyTextureObject_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectResourceDesc_v5000:
      return "cudaGetTextureObjectResourceDesc_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectTextureDesc_v5000:
      return "cudaGetTextureObjectTextureDesc_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaCreateSurfaceObject_v5000:
      return "cudaCreateSurfaceObject_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDestroySurfaceObject_v5000:
      return "cudaDestroySurfaceObject_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetSurfaceObjectResourceDesc_v5000:
      return "cudaGetSurfaceObjectResourceDesc_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMallocMipmappedArray_v5000:
      return "cudaMallocMipmappedArray_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetMipmappedArrayLevel_v5000:
      return "cudaGetMipmappedArrayLevel_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFreeMipmappedArray_v5000:
      return "cudaFreeMipmappedArray_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaBindTextureToMipmappedArray_v5000:
      return "cudaBindTextureToMipmappedArray_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedMipmappedArray_v5000:
      return "cudaGraphicsResourceGetMappedMipmappedArray_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamAddCallback_v5000:
      return "cudaStreamAddCallback_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreateWithFlags_v5000:
      return "cudaStreamCreateWithFlags_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectResourceViewDesc_v5000:
      return "cudaGetTextureObjectResourceViewDesc_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetAttribute_v5000:
      return "cudaDeviceGetAttribute_v5000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamDestroy_v5050:
      return "cudaStreamDestroy_v5050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreateWithPriority_v5050:
      return "cudaStreamCreateWithPriority_v5050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetPriority_v5050:
      return "cudaStreamGetPriority_v5050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetFlags_v5050:
      return "cudaStreamGetFlags_v5050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetStreamPriorityRange_v5050:
      return "cudaDeviceGetStreamPriorityRange_v5050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMallocManaged_v6000:
      return "cudaMallocManaged_v6000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6000:
      return "cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamAttachMemAsync_v6000:
      return "cudaStreamAttachMemAsync_v6000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetErrorName_v6050:
      return "cudaGetErrorName_v6050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6050:
      return "cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6050";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000:
      return "cudaLaunchKernel_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceFlags_v7000:
      return "cudaGetDeviceFlags_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunch_ptsz_v7000:
      return "cudaLaunch_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_ptsz_v7000:
      return "cudaLaunchKernel_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy_ptds_v7000:
      return "cudaMemcpy_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2D_ptds_v7000:
      return "cudaMemcpy2D_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArray_ptds_v7000:
      return "cudaMemcpyToArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArray_ptds_v7000:
      return "cudaMemcpy2DToArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArray_ptds_v7000:
      return "cudaMemcpyFromArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArray_ptds_v7000:
      return "cudaMemcpy2DFromArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyArrayToArray_ptds_v7000:
      return "cudaMemcpyArrayToArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DArrayToArray_ptds_v7000:
      return "cudaMemcpy2DArrayToArray_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbol_ptds_v7000:
      return "cudaMemcpyToSymbol_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbol_ptds_v7000:
      return "cudaMemcpyFromSymbol_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyAsync_ptsz_v7000:
      return "cudaMemcpyAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArrayAsync_ptsz_v7000:
      return "cudaMemcpyToArrayAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArrayAsync_ptsz_v7000:
      return "cudaMemcpyFromArrayAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DAsync_ptsz_v7000:
      return "cudaMemcpy2DAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArrayAsync_ptsz_v7000:
      return "cudaMemcpy2DToArrayAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArrayAsync_ptsz_v7000:
      return "cudaMemcpy2DFromArrayAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbolAsync_ptsz_v7000:
      return "cudaMemcpyToSymbolAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbolAsync_ptsz_v7000:
      return "cudaMemcpyFromSymbolAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset_ptds_v7000:
      return "cudaMemset_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset2D_ptds_v7000:
      return "cudaMemset2D_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemsetAsync_ptsz_v7000:
      return "cudaMemsetAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset2DAsync_ptsz_v7000:
      return "cudaMemset2DAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetPriority_ptsz_v7000:
      return "cudaStreamGetPriority_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetFlags_ptsz_v7000:
      return "cudaStreamGetFlags_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamSynchronize_ptsz_v7000:
      return "cudaStreamSynchronize_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamQuery_ptsz_v7000:
      return "cudaStreamQuery_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamAttachMemAsync_ptsz_v7000:
      return "cudaStreamAttachMemAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventRecord_ptsz_v7000:
      return "cudaEventRecord_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset3D_ptds_v7000:
      return "cudaMemset3D_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemset3DAsync_ptsz_v7000:
      return "cudaMemset3DAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3D_ptds_v7000:
      return "cudaMemcpy3D_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DAsync_ptsz_v7000:
      return "cudaMemcpy3DAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamWaitEvent_ptsz_v7000:
      return "cudaStreamWaitEvent_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaStreamAddCallback_ptsz_v7000:
      return "cudaStreamAddCallback_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeer_ptds_v7000:
      return "cudaMemcpy3DPeer_ptds_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeerAsync_ptsz_v7000:
      return "cudaMemcpy3DPeerAsync_ptsz_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_v7000:
      return "cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_v8000:
      return "cudaMemPrefetchAsync_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_ptsz_v8000:
      return "cudaMemPrefetchAsync_ptsz_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemAdvise_v8000:
      return "cudaMemAdvise_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetP2PAttribute_v8000:
      return "cudaDeviceGetP2PAttribute_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsEGLRegisterImage_v7000:
      return "cudaGraphicsEGLRegisterImage_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerConnect_v7000:
      return "cudaEGLStreamConsumerConnect_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerDisconnect_v7000:
      return "cudaEGLStreamConsumerDisconnect_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerAcquireFrame_v7000:
      return "cudaEGLStreamConsumerAcquireFrame_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerReleaseFrame_v7000:
      return "cudaEGLStreamConsumerReleaseFrame_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerConnect_v7000:
      return "cudaEGLStreamProducerConnect_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerDisconnect_v7000:
      return "cudaEGLStreamProducerDisconnect_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerPresentFrame_v7000:
      return "cudaEGLStreamProducerPresentFrame_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerReturnFrame_v7000:
      return "cudaEGLStreamProducerReturnFrame_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedEglFrame_v7000:
      return "cudaGraphicsResourceGetMappedEglFrame_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemRangeGetAttribute_v8000:
      return "cudaMemRangeGetAttribute_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaMemRangeGetAttributes_v8000:
      return "cudaMemRangeGetAttributes_v8000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerConnectWithFlags_v7000:
      return "cudaEGLStreamConsumerConnectWithFlags_v7000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernel_v9000:
      return "cudaLaunchCooperativeKernel_v9000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernel_ptsz_v9000:
      return "cudaLaunchCooperativeKernel_ptsz_v9000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaEventCreateFromEGLSync_v9000:
      return "cudaEventCreateFromEGLSync_v9000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernelMultiDevice_v9000:
      return "cudaLaunchCooperativeKernelMultiDevice_v9000";
    case CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetAttribute_v9000:
      return "cudaFuncSetAttribute_v9000";
    case CUPTI_RUNTIME_TRACE_CBID_SIZE:
      return "SIZE";
    case CUPTI_RUNTIME_TRACE_CBID_FORCE_INT:
      return "FORCE_INT";
    default:
      return "   <unknown>";
    }
}


static const char *
getDriverApiKindString(CUpti_CallbackId kind)
{
  switch (kind) 
  {
    case CUPTI_DRIVER_TRACE_CBID_INVALID:
      return "INVALID";
    case CUPTI_DRIVER_TRACE_CBID_cuInit:
      return "cuInit";
    case CUPTI_DRIVER_TRACE_CBID_cuDriverGetVersion:
      return "cuDriverGetVersion";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGet:
      return "cuDeviceGet";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetCount:
      return "cuDeviceGetCount";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetName:
      return "cuDeviceGetName";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceComputeCapability:
      return "cuDeviceComputeCapability";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceTotalMem:
      return "cuDeviceTotalMem";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetProperties:
      return "cuDeviceGetProperties";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetAttribute:
      return "cuDeviceGetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxCreate:
      return "cuCtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxDestroy:
      return "cuCtxDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxAttach:
      return "cuCtxAttach";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxDetach:
      return "cuCtxDetach";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxPushCurrent:
      return "cuCtxPushCurrent";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxPopCurrent:
      return "cuCtxPopCurrent";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetDevice:
      return "cuCtxGetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxSynchronize:
      return "cuCtxSynchronize";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleLoad:
      return "cuModuleLoad";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleLoadData:
      return "cuModuleLoadData";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleLoadDataEx:
      return "cuModuleLoadDataEx";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleLoadFatBinary:
      return "cuModuleLoadFatBinary";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleUnload:
      return "cuModuleUnload";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleGetFunction:
      return "cuModuleGetFunction";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleGetGlobal:
      return "cuModuleGetGlobal";
    case CUPTI_DRIVER_TRACE_CBID_cu64ModuleGetGlobal:
      return "cu64ModuleGetGlobal";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleGetTexRef:
      return "cuModuleGetTexRef";
    case CUPTI_DRIVER_TRACE_CBID_cuMemGetInfo:
      return "cuMemGetInfo";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemGetInfo:
      return "cu64MemGetInfo";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAlloc:
      return "cuMemAlloc";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemAlloc:
      return "cu64MemAlloc";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAllocPitch:
      return "cuMemAllocPitch";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemAllocPitch:
      return "cu64MemAllocPitch";
    case CUPTI_DRIVER_TRACE_CBID_cuMemFree:
      return "cuMemFree";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemFree:
      return "cu64MemFree";
    case CUPTI_DRIVER_TRACE_CBID_cuMemGetAddressRange:
      return "cuMemGetAddressRange";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemGetAddressRange:
      return "cu64MemGetAddressRange";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAllocHost:
      return "cuMemAllocHost";
    case CUPTI_DRIVER_TRACE_CBID_cuMemFreeHost:
      return "cuMemFreeHost";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostAlloc:
      return "cuMemHostAlloc";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostGetDevicePointer:
      return "cuMemHostGetDevicePointer";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemHostGetDevicePointer:
      return "cu64MemHostGetDevicePointer";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostGetFlags:
      return "cuMemHostGetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD:
      return "cuMemcpyHtoD";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyHtoD:
      return "cu64MemcpyHtoD";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH:
      return "cuMemcpyDtoH";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoH:
      return "cu64MemcpyDtoH";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD:
      return "cuMemcpyDtoD";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoD:
      return "cu64MemcpyDtoD";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA:
      return "cuMemcpyDtoA";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoA:
      return "cu64MemcpyDtoA";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD:
      return "cuMemcpyAtoD";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyAtoD:
      return "cu64MemcpyAtoD";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA:
      return "cuMemcpyHtoA";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH:
      return "cuMemcpyAtoH";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA:
      return "cuMemcpyAtoA";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D:
      return "cuMemcpy2D";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned:
      return "cuMemcpy2DUnaligned";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D:
      return "cuMemcpy3D";
    case CUPTI_DRIVER_TRACE_CBID_cu64Memcpy3D:
      return "cu64Memcpy3D";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync:
      return "cuMemcpyHtoDAsync";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyHtoDAsync:
      return "cu64MemcpyHtoDAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync:
      return "cuMemcpyDtoHAsync";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoHAsync:
      return "cu64MemcpyDtoHAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync:
      return "cuMemcpyDtoDAsync";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemcpyDtoDAsync:
      return "cu64MemcpyDtoDAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync:
      return "cuMemcpyHtoAAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync:
      return "cuMemcpyAtoHAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync:
      return "cuMemcpy2DAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync:
      return "cuMemcpy3DAsync";
    case CUPTI_DRIVER_TRACE_CBID_cu64Memcpy3DAsync:
      return "cu64Memcpy3DAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD8:
      return "cuMemsetD8";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD8:
      return "cu64MemsetD8";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD16:
      return "cuMemsetD16";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD16:
      return "cu64MemsetD16";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD32:
      return "cuMemsetD32";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD32:
      return "cu64MemsetD32";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8:
      return "cuMemsetD2D8";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D8:
      return "cu64MemsetD2D8";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16:
      return "cuMemsetD2D16";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D16:
      return "cu64MemsetD2D16";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32:
      return "cuMemsetD2D32";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D32:
      return "cu64MemsetD2D32";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncSetBlockShape:
      return "cuFuncSetBlockShape";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncSetSharedSize:
      return "cuFuncSetSharedSize";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncGetAttribute:
      return "cuFuncGetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncSetCacheConfig:
      return "cuFuncSetCacheConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuArrayCreate:
      return "cuArrayCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuArrayGetDescriptor:
      return "cuArrayGetDescriptor";
    case CUPTI_DRIVER_TRACE_CBID_cuArrayDestroy:
      return "cuArrayDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuArray3DCreate:
      return "cuArray3DCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuArray3DGetDescriptor:
      return "cuArray3DGetDescriptor";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefCreate:
      return "cuTexRefCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefDestroy:
      return "cuTexRefDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetArray:
      return "cuTexRefSetArray";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress:
      return "cuTexRefSetAddress";
    case CUPTI_DRIVER_TRACE_CBID_cu64TexRefSetAddress:
      return "cu64TexRefSetAddress";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D:
      return "cuTexRefSetAddress2D";
    case CUPTI_DRIVER_TRACE_CBID_cu64TexRefSetAddress2D:
      return "cu64TexRefSetAddress2D";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFormat:
      return "cuTexRefSetFormat";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddressMode:
      return "cuTexRefSetAddressMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFilterMode:
      return "cuTexRefSetFilterMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetFlags:
      return "cuTexRefSetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddress:
      return "cuTexRefGetAddress";
    case CUPTI_DRIVER_TRACE_CBID_cu64TexRefGetAddress:
      return "cu64TexRefGetAddress";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetArray:
      return "cuTexRefGetArray";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddressMode:
      return "cuTexRefGetAddressMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFilterMode:
      return "cuTexRefGetFilterMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFormat:
      return "cuTexRefGetFormat";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetFlags:
      return "cuTexRefGetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuParamSetSize:
      return "cuParamSetSize";
    case CUPTI_DRIVER_TRACE_CBID_cuParamSeti:
      return "cuParamSeti";
    case CUPTI_DRIVER_TRACE_CBID_cuParamSetf:
      return "cuParamSetf";
    case CUPTI_DRIVER_TRACE_CBID_cuParamSetv:
      return "cuParamSetv";
    case CUPTI_DRIVER_TRACE_CBID_cuParamSetTexRef:
      return "cuParamSetTexRef";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunch:
      return "cuLaunch";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchGrid:
      return "cuLaunchGrid";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchGridAsync:
      return "cuLaunchGridAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuEventCreate:
      return "cuEventCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuEventRecord:
      return "cuEventRecord";
    case CUPTI_DRIVER_TRACE_CBID_cuEventQuery:
      return "cuEventQuery";
    case CUPTI_DRIVER_TRACE_CBID_cuEventSynchronize:
      return "cuEventSynchronize";
    case CUPTI_DRIVER_TRACE_CBID_cuEventDestroy:
      return "cuEventDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuEventElapsedTime:
      return "cuEventElapsedTime";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamCreate:
      return "cuStreamCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamQuery:
      return "cuStreamQuery";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamSynchronize:
      return "cuStreamSynchronize";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamDestroy:
      return "cuStreamDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnregisterResource:
      return "cuGraphicsUnregisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsSubResourceGetMappedArray:
      return "cuGraphicsSubResourceGetMappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedPointer:
      return "cuGraphicsResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cu64GraphicsResourceGetMappedPointer:
      return "cu64GraphicsResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceSetMapFlags:
      return "cuGraphicsResourceSetMapFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsMapResources:
      return "cuGraphicsMapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnmapResources:
      return "cuGraphicsUnmapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuGetExportTable:
      return "cuGetExportTable";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxSetLimit:
      return "cuCtxSetLimit";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetLimit:
      return "cuCtxGetLimit";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDevice:
      return "cuD3D10GetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreate:
      return "cuD3D10CtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D10RegisterResource:
      return "cuGraphicsD3D10RegisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10RegisterResource:
      return "cuD3D10RegisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10UnregisterResource:
      return "cuD3D10UnregisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10MapResources:
      return "cuD3D10MapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10UnmapResources:
      return "cuD3D10UnmapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceSetMapFlags:
      return "cuD3D10ResourceSetMapFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedArray:
      return "cuD3D10ResourceGetMappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPointer:
      return "cuD3D10ResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedSize:
      return "cuD3D10ResourceGetMappedSize";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPitch:
      return "cuD3D10ResourceGetMappedPitch";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetSurfaceDimensions:
      return "cuD3D10ResourceGetSurfaceDimensions";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDevice:
      return "cuD3D11GetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreate:
      return "cuD3D11CtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D11RegisterResource:
      return "cuGraphicsD3D11RegisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDevice:
      return "cuD3D9GetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreate:
      return "cuD3D9CtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsD3D9RegisterResource:
      return "cuGraphicsD3D9RegisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDirect3DDevice:
      return "cuD3D9GetDirect3DDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9RegisterResource:
      return "cuD3D9RegisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9UnregisterResource:
      return "cuD3D9UnregisterResource";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9MapResources:
      return "cuD3D9MapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9UnmapResources:
      return "cuD3D9UnmapResources";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceSetMapFlags:
      return "cuD3D9ResourceSetMapFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetSurfaceDimensions:
      return "cuD3D9ResourceGetSurfaceDimensions";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedArray:
      return "cuD3D9ResourceGetMappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPointer:
      return "cuD3D9ResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedSize:
      return "cuD3D9ResourceGetMappedSize";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPitch:
      return "cuD3D9ResourceGetMappedPitch";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9Begin:
      return "cuD3D9Begin";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9End:
      return "cuD3D9End";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9RegisterVertexBuffer:
      return "cuD3D9RegisterVertexBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9MapVertexBuffer:
      return "cuD3D9MapVertexBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9UnmapVertexBuffer:
      return "cuD3D9UnmapVertexBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9UnregisterVertexBuffer:
      return "cuD3D9UnregisterVertexBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cuGLCtxCreate:
      return "cuGLCtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsGLRegisterBuffer:
      return "cuGraphicsGLRegisterBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsGLRegisterImage:
      return "cuGraphicsGLRegisterImage";
    case CUPTI_DRIVER_TRACE_CBID_cuWGLGetDevice:
      return "cuWGLGetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuGLInit:
      return "cuGLInit";
    case CUPTI_DRIVER_TRACE_CBID_cuGLRegisterBufferObject:
      return "cuGLRegisterBufferObject";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject:
      return "cuGLMapBufferObject";
    case CUPTI_DRIVER_TRACE_CBID_cuGLUnmapBufferObject:
      return "cuGLUnmapBufferObject";
    case CUPTI_DRIVER_TRACE_CBID_cuGLUnregisterBufferObject:
      return "cuGLUnregisterBufferObject";
    case CUPTI_DRIVER_TRACE_CBID_cuGLSetBufferObjectMapFlags:
      return "cuGLSetBufferObjectMapFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync:
      return "cuGLMapBufferObjectAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuGLUnmapBufferObjectAsync:
      return "cuGLUnmapBufferObjectAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuVDPAUGetDevice:
      return "cuVDPAUGetDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuVDPAUCtxCreate:
      return "cuVDPAUCtxCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsVDPAURegisterVideoSurface:
      return "cuGraphicsVDPAURegisterVideoSurface";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsVDPAURegisterOutputSurface:
      return "cuGraphicsVDPAURegisterOutputSurface";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleGetSurfRef:
      return "cuModuleGetSurfRef";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefCreate:
      return "cuSurfRefCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefDestroy:
      return "cuSurfRefDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefSetFormat:
      return "cuSurfRefSetFormat";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefSetArray:
      return "cuSurfRefSetArray";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefGetFormat:
      return "cuSurfRefGetFormat";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfRefGetArray:
      return "cuSurfRefGetArray";
    case CUPTI_DRIVER_TRACE_CBID_cu64DeviceTotalMem:
      return "cu64DeviceTotalMem";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedPointer:
      return "cu64D3D10ResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedSize:
      return "cu64D3D10ResourceGetMappedSize";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetMappedPitch:
      return "cu64D3D10ResourceGetMappedPitch";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D10ResourceGetSurfaceDimensions:
      return "cu64D3D10ResourceGetSurfaceDimensions";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetSurfaceDimensions:
      return "cu64D3D9ResourceGetSurfaceDimensions";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedPointer:
      return "cu64D3D9ResourceGetMappedPointer";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedSize:
      return "cu64D3D9ResourceGetMappedSize";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D9ResourceGetMappedPitch:
      return "cu64D3D9ResourceGetMappedPitch";
    case CUPTI_DRIVER_TRACE_CBID_cu64D3D9MapVertexBuffer:
      return "cu64D3D9MapVertexBuffer";
    case CUPTI_DRIVER_TRACE_CBID_cu64GLMapBufferObject:
      return "cu64GLMapBufferObject";
    case CUPTI_DRIVER_TRACE_CBID_cu64GLMapBufferObjectAsync:
      return "cu64GLMapBufferObjectAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDevices:
      return "cuD3D11GetDevices";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreateOnDevice:
      return "cuD3D11CtxCreateOnDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDevices:
      return "cuD3D10GetDevices";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreateOnDevice:
      return "cuD3D10CtxCreateOnDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9GetDevices:
      return "cuD3D9GetDevices";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreateOnDevice:
      return "cuD3D9CtxCreateOnDevice";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemHostAlloc:
      return "cu64MemHostAlloc";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD8Async:
      return "cuMemsetD8Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD8Async:
      return "cu64MemsetD8Async";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD16Async:
      return "cuMemsetD16Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD16Async:
      return "cu64MemsetD16Async";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD32Async:
      return "cuMemsetD32Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD32Async:
      return "cu64MemsetD32Async";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8Async:
      return "cuMemsetD2D8Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D8Async:
      return "cu64MemsetD2D8Async";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16Async:
      return "cuMemsetD2D16Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D16Async:
      return "cu64MemsetD2D16Async";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32Async:
      return "cuMemsetD2D32Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64MemsetD2D32Async:
      return "cu64MemsetD2D32Async";
    case CUPTI_DRIVER_TRACE_CBID_cu64ArrayCreate:
      return "cu64ArrayCreate";
    case CUPTI_DRIVER_TRACE_CBID_cu64ArrayGetDescriptor:
      return "cu64ArrayGetDescriptor";
    case CUPTI_DRIVER_TRACE_CBID_cu64Array3DCreate:
      return "cu64Array3DCreate";
    case CUPTI_DRIVER_TRACE_CBID_cu64Array3DGetDescriptor:
      return "cu64Array3DGetDescriptor";
    case CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2D:
      return "cu64Memcpy2D";
    case CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2DUnaligned:
      return "cu64Memcpy2DUnaligned";
    case CUPTI_DRIVER_TRACE_CBID_cu64Memcpy2DAsync:
      return "cu64Memcpy2DAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxCreate_v2:
      return "cuCtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10CtxCreate_v2:
      return "cuD3D10CtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11CtxCreate_v2:
      return "cuD3D11CtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9CtxCreate_v2:
      return "cuD3D9CtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuGLCtxCreate_v2:
      return "cuGLCtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuVDPAUCtxCreate_v2:
      return "cuVDPAUCtxCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuModuleGetGlobal_v2:
      return "cuModuleGetGlobal_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemGetInfo_v2:
      return "cuMemGetInfo_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAlloc_v2:
      return "cuMemAlloc_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAllocPitch_v2:
      return "cuMemAllocPitch_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemFree_v2:
      return "cuMemFree_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemGetAddressRange_v2:
      return "cuMemGetAddressRange_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostGetDevicePointer_v2:
      return "cuMemHostGetDevicePointer_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy_v2:
      return "cuMemcpy_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD8_v2:
      return "cuMemsetD8_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD16_v2:
      return "cuMemsetD16_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD32_v2:
      return "cuMemsetD32_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8_v2:
      return "cuMemsetD2D8_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16_v2:
      return "cuMemsetD2D16_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32_v2:
      return "cuMemsetD2D32_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress_v2:
      return "cuTexRefSetAddress_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D_v2:
      return "cuTexRefSetAddress2D_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetAddress_v2:
      return "cuTexRefGetAddress_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedPointer_v2:
      return "cuGraphicsResourceGetMappedPointer_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceTotalMem_v2:
      return "cuDeviceTotalMem_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPointer_v2:
      return "cuD3D10ResourceGetMappedPointer_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedSize_v2:
      return "cuD3D10ResourceGetMappedSize_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetMappedPitch_v2:
      return "cuD3D10ResourceGetMappedPitch_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10ResourceGetSurfaceDimensions_v2:
      return "cuD3D10ResourceGetSurfaceDimensions_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetSurfaceDimensions_v2:
      return "cuD3D9ResourceGetSurfaceDimensions_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPointer_v2:
      return "cuD3D9ResourceGetMappedPointer_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedSize_v2:
      return "cuD3D9ResourceGetMappedSize_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9ResourceGetMappedPitch_v2:
      return "cuD3D9ResourceGetMappedPitch_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D9MapVertexBuffer_v2:
      return "cuD3D9MapVertexBuffer_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject_v2:
      return "cuGLMapBufferObject_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync_v2:
      return "cuGLMapBufferObjectAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostAlloc_v2:
      return "cuMemHostAlloc_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuArrayCreate_v2:
      return "cuArrayCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuArrayGetDescriptor_v2:
      return "cuArrayGetDescriptor_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuArray3DCreate_v2:
      return "cuArray3DCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuArray3DGetDescriptor_v2:
      return "cuArray3DGetDescriptor_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD_v2:
      return "cuMemcpyHtoD_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync_v2:
      return "cuMemcpyHtoDAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH_v2:
      return "cuMemcpyDtoH_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync_v2:
      return "cuMemcpyDtoHAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD_v2:
      return "cuMemcpyDtoD_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync_v2:
      return "cuMemcpyDtoDAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH_v2:
      return "cuMemcpyAtoH_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync_v2:
      return "cuMemcpyAtoHAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD_v2:
      return "cuMemcpyAtoD_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA_v2:
      return "cuMemcpyDtoA_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA_v2:
      return "cuMemcpyAtoA_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D_v2:
      return "cuMemcpy2D_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned_v2:
      return "cuMemcpy2DUnaligned_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync_v2:
      return "cuMemcpy2DAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D_v2:
      return "cuMemcpy3D_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync_v2:
      return "cuMemcpy3DAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA_v2:
      return "cuMemcpyHtoA_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync_v2:
      return "cuMemcpyHtoAAsync_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAllocHost_v2:
      return "cuMemAllocHost_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitEvent:
      return "cuStreamWaitEvent";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetApiVersion:
      return "cuCtxGetApiVersion";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D10GetDirect3DDevice:
      return "cuD3D10GetDirect3DDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuD3D11GetDirect3DDevice:
      return "cuD3D11GetDirect3DDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetCacheConfig:
      return "cuCtxGetCacheConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxSetCacheConfig:
      return "cuCtxSetCacheConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostRegister:
      return "cuMemHostRegister";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostUnregister:
      return "cuMemHostUnregister";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxSetCurrent:
      return "cuCtxSetCurrent";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetCurrent:
      return "cuCtxGetCurrent";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy:
      return "cuMemcpy";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAsync:
      return "cuMemcpyAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchKernel:
      return "cuLaunchKernel";
    case CUPTI_DRIVER_TRACE_CBID_cuProfilerStart:
      return "cuProfilerStart";
    case CUPTI_DRIVER_TRACE_CBID_cuProfilerStop:
      return "cuProfilerStop";
    case CUPTI_DRIVER_TRACE_CBID_cuPointerGetAttribute:
      return "cuPointerGetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuProfilerInitialize:
      return "cuProfilerInitialize";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceCanAccessPeer:
      return "cuDeviceCanAccessPeer";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxEnablePeerAccess:
      return "cuCtxEnablePeerAccess";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxDisablePeerAccess:
      return "cuCtxDisablePeerAccess";
    case CUPTI_DRIVER_TRACE_CBID_cuMemPeerRegister:
      return "cuMemPeerRegister";
    case CUPTI_DRIVER_TRACE_CBID_cuMemPeerUnregister:
      return "cuMemPeerUnregister";
    case CUPTI_DRIVER_TRACE_CBID_cuMemPeerGetDevicePointer:
      return "cuMemPeerGetDevicePointer";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeer:
      return "cuMemcpyPeer";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeerAsync:
      return "cuMemcpyPeerAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeer:
      return "cuMemcpy3DPeer";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeerAsync:
      return "cuMemcpy3DPeerAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxDestroy_v2:
      return "cuCtxDestroy_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxPushCurrent_v2:
      return "cuCtxPushCurrent_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxPopCurrent_v2:
      return "cuCtxPopCurrent_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuEventDestroy_v2:
      return "cuEventDestroy_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamDestroy_v2:
      return "cuStreamDestroy_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetAddress2D_v3:
      return "cuTexRefSetAddress2D_v3";
    case CUPTI_DRIVER_TRACE_CBID_cuIpcGetMemHandle:
      return "cuIpcGetMemHandle";
    case CUPTI_DRIVER_TRACE_CBID_cuIpcOpenMemHandle:
      return "cuIpcOpenMemHandle";
    case CUPTI_DRIVER_TRACE_CBID_cuIpcCloseMemHandle:
      return "cuIpcCloseMemHandle";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetByPCIBusId:
      return "cuDeviceGetByPCIBusId";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetPCIBusId:
      return "cuDeviceGetPCIBusId";
    case CUPTI_DRIVER_TRACE_CBID_cuGLGetDevices:
      return "cuGLGetDevices";
    case CUPTI_DRIVER_TRACE_CBID_cuIpcGetEventHandle:
      return "cuIpcGetEventHandle";
    case CUPTI_DRIVER_TRACE_CBID_cuIpcOpenEventHandle:
      return "cuIpcOpenEventHandle";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxSetSharedMemConfig:
      return "cuCtxSetSharedMemConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetSharedMemConfig:
      return "cuCtxGetSharedMemConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncSetSharedMemConfig:
      return "cuFuncSetSharedMemConfig";
    case CUPTI_DRIVER_TRACE_CBID_cuTexObjectCreate:
      return "cuTexObjectCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuTexObjectDestroy:
      return "cuTexObjectDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetResourceDesc:
      return "cuTexObjectGetResourceDesc";
    case CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetTextureDesc:
      return "cuTexObjectGetTextureDesc";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfObjectCreate:
      return "cuSurfObjectCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfObjectDestroy:
      return "cuSurfObjectDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuSurfObjectGetResourceDesc:
      return "cuSurfObjectGetResourceDesc";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamAddCallback:
      return "cuStreamAddCallback";
    case CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayCreate:
      return "cuMipmappedArrayCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayGetLevel:
      return "cuMipmappedArrayGetLevel";
    case CUPTI_DRIVER_TRACE_CBID_cuMipmappedArrayDestroy:
      return "cuMipmappedArrayDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmappedArray:
      return "cuTexRefSetMipmappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapFilterMode:
      return "cuTexRefSetMipmapFilterMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapLevelBias:
      return "cuTexRefSetMipmapLevelBias";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMipmapLevelClamp:
      return "cuTexRefSetMipmapLevelClamp";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetMaxAnisotropy:
      return "cuTexRefSetMaxAnisotropy";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmappedArray:
      return "cuTexRefGetMipmappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapFilterMode:
      return "cuTexRefGetMipmapFilterMode";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapLevelBias:
      return "cuTexRefGetMipmapLevelBias";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMipmapLevelClamp:
      return "cuTexRefGetMipmapLevelClamp";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetMaxAnisotropy:
      return "cuTexRefGetMaxAnisotropy";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedMipmappedArray:
      return "cuGraphicsResourceGetMappedMipmappedArray";
    case CUPTI_DRIVER_TRACE_CBID_cuTexObjectGetResourceViewDesc:
      return "cuTexObjectGetResourceViewDesc";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkCreate:
      return "cuLinkCreate";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkAddData:
      return "cuLinkAddData";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkAddFile:
      return "cuLinkAddFile";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkComplete:
      return "cuLinkComplete";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkDestroy:
      return "cuLinkDestroy";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamCreateWithPriority:
      return "cuStreamCreateWithPriority";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetPriority:
      return "cuStreamGetPriority";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetFlags:
      return "cuStreamGetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetStreamPriorityRange:
      return "cuCtxGetStreamPriorityRange";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAllocManaged:
      return "cuMemAllocManaged";
    case CUPTI_DRIVER_TRACE_CBID_cuGetErrorString:
      return "cuGetErrorString";
    case CUPTI_DRIVER_TRACE_CBID_cuGetErrorName:
      return "cuGetErrorName";
    case CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxActiveBlocksPerMultiprocessor:
      return "cuOccupancyMaxActiveBlocksPerMultiprocessor";
    case CUPTI_DRIVER_TRACE_CBID_cuCompilePtx:
      return "cuCompilePtx";
    case CUPTI_DRIVER_TRACE_CBID_cuBinaryFree:
      return "cuBinaryFree";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamAttachMemAsync:
      return "cuStreamAttachMemAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuPointerSetAttribute:
      return "cuPointerSetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuMemHostRegister_v2:
      return "cuMemHostRegister_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceSetMapFlags_v2:
      return "cuGraphicsResourceSetMapFlags_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkCreate_v2:
      return "cuLinkCreate_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkAddData_v2:
      return "cuLinkAddData_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuLinkAddFile_v2:
      return "cuLinkAddFile_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxPotentialBlockSize:
      return "cuOccupancyMaxPotentialBlockSize";
    case CUPTI_DRIVER_TRACE_CBID_cuGLGetDevices_v2:
      return "cuGLGetDevices_v2";
    case CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxRetain:
      return "cuDevicePrimaryCtxRetain";
    case CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxRelease:
      return "cuDevicePrimaryCtxRelease";
    case CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxSetFlags:
      return "cuDevicePrimaryCtxSetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxReset:
      return "cuDevicePrimaryCtxReset";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsEGLRegisterImage:
      return "cuGraphicsEGLRegisterImage";
    case CUPTI_DRIVER_TRACE_CBID_cuCtxGetFlags:
      return "cuCtxGetFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuDevicePrimaryCtxGetState:
      return "cuDevicePrimaryCtxGetState";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerConnect:
      return "cuEGLStreamConsumerConnect";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerDisconnect:
      return "cuEGLStreamConsumerDisconnect";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerAcquireFrame:
      return "cuEGLStreamConsumerAcquireFrame";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerReleaseFrame:
      return "cuEGLStreamConsumerReleaseFrame";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoD_v2_ptds:
      return "cuMemcpyHtoD_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoH_v2_ptds:
      return "cuMemcpyDtoH_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoD_v2_ptds:
      return "cuMemcpyDtoD_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoA_v2_ptds:
      return "cuMemcpyDtoA_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoD_v2_ptds:
      return "cuMemcpyAtoD_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoA_v2_ptds:
      return "cuMemcpyHtoA_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoH_v2_ptds:
      return "cuMemcpyAtoH_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoA_v2_ptds:
      return "cuMemcpyAtoA_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2D_v2_ptds:
      return "cuMemcpy2D_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DUnaligned_v2_ptds:
      return "cuMemcpy2DUnaligned_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3D_v2_ptds:
      return "cuMemcpy3D_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy_ptds:
      return "cuMemcpy_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeer_ptds:
      return "cuMemcpyPeer_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeer_ptds:
      return "cuMemcpy3DPeer_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD8_v2_ptds:
      return "cuMemsetD8_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD16_v2_ptds:
      return "cuMemsetD16_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD32_v2_ptds:
      return "cuMemsetD32_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8_v2_ptds:
      return "cuMemsetD2D8_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16_v2_ptds:
      return "cuMemsetD2D16_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32_v2_ptds:
      return "cuMemsetD2D32_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObject_v2_ptds:
      return "cuGLMapBufferObject_v2_ptds";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAsync_ptsz:
      return "cuMemcpyAsync_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoAAsync_v2_ptsz:
      return "cuMemcpyHtoAAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyAtoHAsync_v2_ptsz:
      return "cuMemcpyAtoHAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyHtoDAsync_v2_ptsz:
      return "cuMemcpyHtoDAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoHAsync_v2_ptsz:
      return "cuMemcpyDtoHAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyDtoDAsync_v2_ptsz:
      return "cuMemcpyDtoDAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy2DAsync_v2_ptsz:
      return "cuMemcpy2DAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DAsync_v2_ptsz:
      return "cuMemcpy3DAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpyPeerAsync_ptsz:
      return "cuMemcpyPeerAsync_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemcpy3DPeerAsync_ptsz:
      return "cuMemcpy3DPeerAsync_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD8Async_ptsz:
      return "cuMemsetD8Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD16Async_ptsz:
      return "cuMemsetD16Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD32Async_ptsz:
      return "cuMemsetD32Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D8Async_ptsz:
      return "cuMemsetD2D8Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D16Async_ptsz:
      return "cuMemsetD2D16Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuMemsetD2D32Async_ptsz:
      return "cuMemsetD2D32Async_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetPriority_ptsz:
      return "cuStreamGetPriority_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetFlags_ptsz:
      return "cuStreamGetFlags_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitEvent_ptsz:
      return "cuStreamWaitEvent_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamAddCallback_ptsz:
      return "cuStreamAddCallback_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamAttachMemAsync_ptsz:
      return "cuStreamAttachMemAsync_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamQuery_ptsz:
      return "cuStreamQuery_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamSynchronize_ptsz:
      return "cuStreamSynchronize_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuEventRecord_ptsz:
      return "cuEventRecord_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchKernel_ptsz:
      return "cuLaunchKernel_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsMapResources_ptsz:
      return "cuGraphicsMapResources_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsUnmapResources_ptsz:
      return "cuGraphicsUnmapResources_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuGLMapBufferObjectAsync_v2_ptsz:
      return "cuGLMapBufferObjectAsync_v2_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerConnect:
      return "cuEGLStreamProducerConnect";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerDisconnect:
      return "cuEGLStreamProducerDisconnect";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerPresentFrame:
      return "cuEGLStreamProducerPresentFrame";
    case CUPTI_DRIVER_TRACE_CBID_cuGraphicsResourceGetMappedEglFrame:
      return "cuGraphicsResourceGetMappedEglFrame";
    case CUPTI_DRIVER_TRACE_CBID_cuPointerGetAttributes:
      return "cuPointerGetAttributes";
    case CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags:
      return "cuOccupancyMaxActiveBlocksPerMultiprocessorWithFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuOccupancyMaxPotentialBlockSizeWithFlags:
      return "cuOccupancyMaxPotentialBlockSizeWithFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamProducerReturnFrame:
      return "cuEGLStreamProducerReturnFrame";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetP2PAttribute:
      return "cuDeviceGetP2PAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefSetBorderColor:
      return "cuTexRefSetBorderColor";
    case CUPTI_DRIVER_TRACE_CBID_cuTexRefGetBorderColor:
      return "cuTexRefGetBorderColor";
    case CUPTI_DRIVER_TRACE_CBID_cuMemAdvise:
      return "cuMemAdvise";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32:
      return "cuStreamWaitValue32";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue32_ptsz:
      return "cuStreamWaitValue32_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32:
      return "cuStreamWriteValue32";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue32_ptsz:
      return "cuStreamWriteValue32_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp:
      return "cuStreamBatchMemOp";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamBatchMemOp_ptsz:
      return "cuStreamBatchMemOp_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuNVNbufferGetPointer:
      return "cuNVNbufferGetPointer";
    case CUPTI_DRIVER_TRACE_CBID_cuNVNtextureGetArray:
      return "cuNVNtextureGetArray";
    case CUPTI_DRIVER_TRACE_CBID_cuNNSetAllocator:
      return "cuNNSetAllocator";
    case CUPTI_DRIVER_TRACE_CBID_cuMemPrefetchAsync:
      return "cuMemPrefetchAsync";
    case CUPTI_DRIVER_TRACE_CBID_cuMemPrefetchAsync_ptsz:
      return "cuMemPrefetchAsync_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuEventCreateFromNVNSync:
      return "cuEventCreateFromNVNSync";
    case CUPTI_DRIVER_TRACE_CBID_cuEGLStreamConsumerConnectWithFlags:
      return "cuEGLStreamConsumerConnectWithFlags";
    case CUPTI_DRIVER_TRACE_CBID_cuMemRangeGetAttribute:
      return "cuMemRangeGetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuMemRangeGetAttributes:
      return "cuMemRangeGetAttributes";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64:
      return "cuStreamWaitValue64";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWaitValue64_ptsz:
      return "cuStreamWaitValue64_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64:
      return "cuStreamWriteValue64";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamWriteValue64_ptsz:
      return "cuStreamWriteValue64_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernel:
      return "cuLaunchCooperativeKernel";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernel_ptsz:
      return "cuLaunchCooperativeKernel_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_cuEventCreateFromEGLSync:
      return "cuEventCreateFromEGLSync";
    case CUPTI_DRIVER_TRACE_CBID_cuLaunchCooperativeKernelMultiDevice:
      return "cuLaunchCooperativeKernelMultiDevice";
    case CUPTI_DRIVER_TRACE_CBID_cuFuncSetAttribute:
      return "cuFuncSetAttribute";
    case CUPTI_DRIVER_TRACE_CBID_cuDeviceGetUuid:
      return "cuDeviceGetUuid";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetCtx:
      return "cuStreamGetCtx";
    case CUPTI_DRIVER_TRACE_CBID_cuStreamGetCtx_ptsz:
      return "cuStreamGetCtx_ptsz";
    case CUPTI_DRIVER_TRACE_CBID_SIZE:
      return "SIZE";
    case CUPTI_DRIVER_TRACE_CBID_FORCE_INT:
      return "FORCE_INT";
    default:
      return "   <unknown>";
  }
}

